# 使用 node 作為基礎映像
FROM node:16

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json
COPY package*.json ./

# 安裝依賴
RUN npm install

# 複製所有文件到容器內
COPY . .

# 構建 React 應用
RUN npm run build

# 曝露應用端口
EXPOSE 3000

# 運行應用
CMD ["npm", "start"]