version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: joeban
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /Users/hongbangzhou/sign_projects/deno-mongoDB/mongodb-log:/data/db
    networks:
      - some-network
    ports:
      - "27017:27017"

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: joeban
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: joeban
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
    networks:
      - some-network
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - 3000:3000
    networks:
      - some-network

  deno-api:
    build:
      context: ./deno-api
    container_name: deno-api
    ports:
      - "8000:8000"
    networks:
      - some-network

networks:
  some-network:
    driver: bridge